import React from 'react';

class Terms extends React.Component {
    render() {
        return (
        <div className="Tos row back">
                <div className="column">
                    <h2 className="above">Steem Crawl Terms of Service</h2>
                    <p className="c0 above"><span
                        className="c1 c2">Last Updated April 28, 2016</span></p><p className="c0"><span
                    className="c1 above">Welcome to Steem Crawl! These Terms of Service (&ldquo;</span><span className="c1 c2">Terms</span><span className="c1">&rdquo;) apply to your access to and use of steemcrawl.com and any other products or services that link to these Terms (&ldquo;</span><span
                    className="c1 c2">Steem Crawl</span><span className="c1">&rdquo;). Steem Crawl is provided by Steem Crawl, (&ldquo;</span><span
                    className="c1 c2">Steem Crawl</span><span className="c1">&rdquo;, &ldquo;</span><span className="c1 c2">we</span><span className="c1">&rdquo;
                    or &ldquo;</span><span className="c1 c2">us</span><span className="c1">&rdquo;). By accessing or using Steem Crawl, you agree to be bound by these Terms. If you do not agree to these Terms, including the mandatory arbitration provision and class action waiver in Section 14, do not access or use Steem Crawl. If we make changes to these Terms, we will provide notice of those changes by updating the &ldquo;</span><span
                    className="c1 c2">Last Updated</span><span className="c1">&rdquo; date above or posting notice on Steem Crawl. Your continued use of Steem Crawl will confirm your acceptance of the changes.</span>
                </p><p className="c0"><span className="c1 h">You understand and agree that these Terms apply solely to your access to, and use of, Steem Crawl and that, when you use Steem Crawl services, the terms and policies particular to those services apply.</span>
                </p><p className="c0"><span className="c1 h">1. Privacy Policy</span></p><p className="c0"><span className="c1">Please refer to our Privacy Policy for information about how we collect, use and disclose information about you.</span>
                </p><p className="c0"><span className="c1 h">2. Eligibility</span></p><p className="c0"><span className="c1">Steem Crawl is not targeted towards, nor intended for use by, anyone under the age of 13. You must be at least 13 years of age to access or use Steem Crawl. If you are between 13 and 18 years of age (or the age of legal majority where you reside), you may only access or use Steem Crawl under the supervision of a parent or legal guardian who agrees to be bound by these Terms.</span>
                </p><p className="c0"><span className="c1 h">3. Copyright and Limited License</span></p><p className="c0"><span className="c1">Steem Crawl Content is protected by intellectual property laws, including copyright and other proprietary rights of the United States and foreign countries. Except as explicitly stated in these Terms, Steem Crawl does not grant any express or implied rights to use Steem Crawl Content.
                </span>
                </p><p className="c0"><span className="c1 h">4. Adult-Oriented Content</span></p><p className="c0"><span className="c1">Steem Crawl is intended for a general audience and, as a result, some Steem Crawl Content may discuss or depict adult-oriented topics. We realize that this content may not be appropriate or desirable for some of our readers depending on their current location, age, background or personal views. As a result, we mark this content as Not Safe For Work (&ldquo;</span><span
                    className="c1 c2">NSFW</span><span className="c1">&rdquo;).</span></p><p className="c0"><span className="c1">Marking Steem Crawl Content as NSFW does not prevent you from being able to access this content but, instead, helps you make informed decisions about the type of content you view on Steem Crawl. You understand and agree that you access content marked as NSFW at your own risk.</span>
                </p><p className="c0"><span className="c1 h">5. Trademarks</span></p><p className="c0"><span className="c1"> &ldquo;
                    Steem Crawl,&rdquo; the Steem Crawl logo and any other product or service names, logos or slogans that may appear on Steem Crawl are trademarks of Steem Crawl and may not be copied, imitated or used, in whole or in part, without our prior written permission. You may not use any metatags or other &ldquo;
                    hidden text&rdquo; utilizing &ldquo;Steem Crawl&rdquo; or any other name, trademark or product or service name of Steem Crawl without our prior written permission. In addition, the look and feel of Steem Crawl, including, without limitation, all page headers, custom graphics, button icons and scripts, constitute the service mark, trademark or trade dress of Steem Crawl and may not be copied, imitated or used, in whole or in part, without our prior written permission. All other trademarks, registered trademarks, product names and company names or logos mentioned or used on Steem Crawl are the property of their respective owners and may not be copied, imitated or used, in whole or in part, without the permission of the applicable trademark holder. Reference to any products, services, processes or other information by name, trademark, manufacturer, supplier or otherwise does not constitute or imply endorsement, sponsorship or recommendation by Steem Crawl.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
                </p><p className="c0"><span className="c1 h">6. Agreement to Hold Steem Crawl Harmless</span></p><p className="c0"><span className="c1">6.1. &nbsp;You agree to hold harmless Steem Crawl (and each of our officers, directors, members, employees, agents and affiliates) from any claim, demand, action, damage, loss, cost or expense, including without limitation reasonable legal fees, arising out or relating to:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
                </p><p className="c0"><span className="c1">6.1.1. &nbsp;Your use of, or conduct in connection with, our Services;</span></p><p
                    className="c0"><span
                    className="c1">6.1.2. &nbsp;Any feedback or submissions you provide (see 19 below);</span></p><p className="c0"><span
                    className="c1">6.1.3. &nbsp;
                    Your violation of these Terms; or</span></p><p className="c0"><span className="c1">6.1.4. &nbsp;Violation of any rights of any other person or entity.</span>
                </p><p className="c0 c5"><span className="c1">6.2. &nbsp;If you are obligated to indemnify us, we will have the right, in our sole discretion, to control any action or proceeding (at our expense) and determine whether we wish to settle it.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
                </p><p className="c0"><span className="c1 h">7. No Liability For Third Party Services And Content</span></p><p className="c0"><span
                    className="c1">7.1. In using our Services, you may view content or utilize services provided by third parties, including links to web pages and services of such parties (&ldquo;
                    Third Party Content&rdquo;). We do not control, endorse or adopt any Third-Party Content and will have no responsibility for Third Party Content including, without limitation, material that may be misleading, incomplete, erroneous, offensive, indecent or otherwise objectionable in your jurisdiction. In addition, your dealings or correspondence with such third parties are solely between you and the third parties. We are not responsible or liable for any loss or damage of any sort incurred as a result of any such dealings and you understand that your use of Third Party Content, and your interactions with third parties, is at your own risk.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
                </p><p className="c0"><span className="c1 h">8. User Conduct</span></p><p className="c0"><span className="c1">8.1. When accessing or using the Services, you agree that you will not commit any unlawful act, and that you are solely responsible for your conduct while using our Services. Without limiting the generality of the foregoing, you agree that you will not:</span>
                </p><p className="c0"><span className="c1">8.1.1. Use our Services in any manner that could interfere with, disrupt, negatively affect or inhibit other users from fully enjoying our Services, or that could damage, disable, overburden or impair the functioning of our Services in any manner;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
                </p><p className="c0"><span className="c1">8.1.2. &nbsp;Use our Services to pay for, support or otherwise engage in any illegal activities, including, but not limited to illegal gambling, fraud, money- laundering, or terrorist activities.</span>
                </p><p className="c0"><span className="c1">8.1.3. &nbsp;Use any robot, spider, crawler, scraper or other automated means or interface not provided by us to access our Services or to extract data;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
                </p><p className="c0"><span className="c1">8.1.4. &nbsp;Use or attempt to use another user&rsquo;s Wallet without authorization;</span></p><p
                    className="c0"><span className="c1">8.1.5. &nbsp;Attempt to circumvent any content filtering techniques we employ, or attempt to access any service or area of our Services that you are not authorized to access;</span>
                </p><p className="c0"><span className="c1">8.1.6. &nbsp;
                    Introduce to the Services any virus, Trojan, worms, logic bombs or other harmful material;</span></p><p className="c0"><span className="c1">8.1.7. &nbsp;
                    Develop any third-party applications that interact with our Services without our prior written consent;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
                </p><p className="c0"><span className="c1">8.1.8. &nbsp;
                    Provide false, inaccurate, or misleading information; or&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
                </p><p className="c0"><span className="c1">8.1.9. &nbsp;Encourage or induce any third party to engage in any of the activities prohibited under this Section. &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
                </p><p className="c6"><span className="c1">8.1.10. &nbsp;Reverse engineer any aspect of Steem Crawl or do anything that might discover source code or bypass or circumvent measures employed to prevent or limit access to any Steem Crawl Content, area or code of Steem Crawl.</span>
                </p><p className="c6 c9"><span className="c1"></span></p><p className="c0"><span className="c1 h">9. Third-Party Content and Sites</span></p><p
                    className="c0">
                        <span
                            className="c1">Steem Crawl may include links and other content owned or operated by third parties, including advertisements and social &ldquo;
                            widgets&rdquo; (we call these &ldquo;</span><span className="c1 c2">Third-Party Content</span><span className="c1">&ldquo;). You agree that Steem Crawl is not responsible or liable for Third-Party Content and that you access and use Third-Party Content at your own risk. Your interactions with Third-Party Content are solely between you and the third party providing the content. When you leave Steem Crawl, you should understand that these Terms no longer govern and that the terms and policies of those third-party sites or services will then apply.</span>
                </p><p className="c6 c9"><span className="c1"></span></p><p className="c0"><span className="c1 h">10. Feedback</span></p><p className="c0"><span
                    className="c1">You may submit questions, comments, feedback, suggestions, and other information regarding Steem Crawl (we call this &ldquo;</span><span
                    className="c1 c2">Feedback</span><span className="c1">&ldquo;). You acknowledge and agree that Feedback is non-confidential and will become the sole property of Steem Crawl. Steem Crawl shall own exclusive rights, including, without limitation, all intellectual property rights, in and to such Feedback and is entitled to the unrestricted use and dissemination of this Feedback for any purpose, without acknowledgment or compensation to you. You agree to execute any documentation required by Steem Crawl to confirm such assignment to Steem Crawl.</span>
                </p><p className="c0"><span className="c1 h">11. Copyright Complaints</span></p><p className="c0"><span className="c1">Steem Crawl respects the intellectual property of others by not reading infringed content from the Steem blockchain. If you believe that your work has been copied in a way that constitutes copyright infringement, you may notify Steem Crawl&rsquo;
                    s Designated Agent by contacting:</span></p><p className="c0"><span className="c1">steemcrawl@mail.com</span></p><p className="c0"><span
                    className="c1">Please see </span><span
                    className="c4"><a className="c3"
                                      href="https://www.google.com/url?q=http://www.copyright.gov/title17/92chap5.html%23512&amp;sa=D&amp;ust=1461884744550000&amp;usg=AFQjCNE4ly_OjjjUlafeWFDM_cOnARywLA">17
                    U.S.C. &sect;512(c)(3)</a></span><span className="c1">&nbsp;for the requirements of a proper notification. You should note that if you knowingly misrepresent in your notification that the material or activity is infringing, you may be liable for any damages, including costs and attorneys&rsquo;
                    fees, incurred by Steem Crawl or the alleged infringer, as the result of Steem Crawl&rsquo;s relying upon such misrepresentation in removing or disabling access to the material or activity claimed to be infringing.</span>
                </p><p className="c0"><span className="c1 h">12. Disclaimers</span></p><p className="c0"><span className="c1">TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, Steem Crawl AND THE Steem Crawl CONTENT ARE PROVIDED ON AN &ldquo;
                    AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT AND ANY WARRANTIES IMPLIED BY ANY COURSE OF PERFORMANCE OR USAGE OF TRADE. Steem Crawl DOES NOT REPRESENT OR WARRANT THAT Steem Crawl AND THE Steem Crawl CONTENT: (A) WILL BE SECURE OR AVAILABLE AT ANY PARTICULAR TIME OR LOCATION; (B) ARE ACCURATE, COMPLETE, RELIABLE, CURRENT OR ERROR-FREE OR THAT ANY DEFECTS OR ERRORS WILL BE CORRECTED; AND (C) ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. YOUR USE OF Steem Crawl AND THE Steem Crawl CONTENT IS SOLELY AT YOUR OWN RISK. SOME JURISDICTIONS DO NOT ALLOW THE DISCLAIMER OF IMPLIED TERMS IN CONTRACTS WITH CONSUMERS, SO SOME OR ALL OF THE DISCLAIMERS IN THIS SECTION MAY NOT APPLY TO YOU.</span>
                </p><p className="c0"><span className="c1 h">13. Limitation of Liability</span></p><p className="c0"><span className="c1">TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL Steem Crawl OR THE Steem Crawl PARTIES BE LIABLE FOR ANY SPECIAL, INDIRECT, INCIDENTAL, CONSEQUENTIAL, EXEMPLARY OR PUNITIVE DAMAGES, OR ANY OTHER DAMAGES OF ANY KIND, INCLUDING, BUT NOT LIMITED TO, LOSS OF USE, LOSS OF PROFITS OR LOSS OF DATA, WHETHER IN AN ACTION IN CONTRACT, TORT (INCLUDING, BUT NOT LIMITED TO, NEGLIGENCE) OR OTHERWISE, ARISING OUT OF, OR IN ANY WAY CONNECTED WITH, THE USE OF, OR INABILITY TO USE, Steem Crawl OR THE Steem Crawl CONTENT. TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL THE AGGREGATE LIABILITY OF Steem Crawl OR THE Steem Crawl PARTIES, WHETHER IN CONTRACT, WARRANTY, TORT (INCLUDING NEGLIGENCE, WHETHER ACTIVE, PASSIVE OR IMPUTED), PRODUCT LIABILITY, STRICT LIABILITY OR OTHER THEORY, ARISING OUT OF OR RELATING TO: (A) THE USE OF OR INABILITY TO USE Steem Crawl OR THE Steem Crawl CONTENT; OR (B) THESE TERMS EXCEED ANY COMPENSATION YOU PAY, IF ANY, TO Steem Crawl FOR ACCESS TO OR USE OF Steem Crawl.</span>
                </p><p className="c0"><span className="c1">SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES, SO SOME OR ALL OF THE EXCLUSIONS AND LIMITATIONS IN THIS SECTION MAY NOT APPLY TO YOU.</span>
                </p><p className="c0"><span className="c1 h">14. Modifications to Steem Crawl</span></p><p className="c0"><span className="c1">Steem Crawl reserves the right to modify or discontinue, temporarily or permanently, Steem Crawl, or any features or portions of Steem Crawl, without prior notice. You agree that Steem Crawl will not be liable for any modification, suspension or discontinuance of Steem Crawl, or any part of Steem Crawl.</span>
                </p><p className="c0"><span className="c1 h">15. Arbitration</span></p><p className="c0"><span className="c1">PLEASE READ THE FOLLOWING SECTION CAREFULLY BECAUSE IT REQUIRES YOU TO ARBITRATE CERTAIN DISPUTES WITH Steem Crawl AND LIMITS THE MANNER IN WHICH YOU CAN SEEK RELIEF FROM Steem Crawl.</span>
                </p><p className="c0"><span className="c1">15.1. Binding Arbitration</span></p><p className="c0"><span className="c1">Except for disputes in which either party seeks to bring an individual action in small claims court or seeks injunctive or other equitable relief for the alleged unlawful use of copyrights, trademarks, trade names, logos, trade secrets or patents, you and Steem Crawl: (a) waive your right to have any and all disputes or Claims arising from these Terms or Steem Crawl (collectively, &ldquo;</span><span
                    className="c1 c2">Disputes</span><span className="c1">&ldquo;) resolved in a court; and (b) waive your right to a jury trial. Instead, you and Steem Crawl will arbitrate Disputes through binding arbitration (which is the referral of a Dispute to one or more persons charged with reviewing the Dispute and making a final and binding determination to resolve it, instead of having the Dispute decided by a judge or jury in court).</span>
                </p><p className="c0"><span className="c1">15.2. No Class Arbitrations, Class Actions or Representative Actions</span></p><p
                    className="c0"><span
                    className="c1">YOU AND Steem Crawl AGREE THAT ANY DISPUTE IS PERSONAL TO YOU AND Steem Crawl AND THAT ANY SUCH DISPUTE WILL BE RESOLVED SOLELY THROUGH INDIVIDUAL ARBITRATION AND WILL NOT BE BROUGHT AS A CLASS ARBITRATION, CLASS ACTION OR ANY OTHER TYPE OF REPRESENTATIVE PROCEEDING. NEITHER PARTY AGREES TO CLASS ARBITRATION OR TO AN ARBITRATION IN WHICH AN INDIVIDUAL ATTEMPTS TO RESOLVE A DISPUTE AS A REPRESENTATIVE OF ANOTHER INDIVIDUAL OR GROUP OF INDIVIDUALS. FURTHER, YOU AND Steem Crawl AGREE THAT A DISPUTE CANNOT BE BROUGHT AS A CLASS, OR OTHER TYPE OF REPRESENTATIVE ACTION, WHETHER WITHIN OR OUTSIDE OF ARBITRATION, OR ON BEHALF OF ANY OTHER INDIVIDUAL OR GROUP OF INDIVIDUALS.</span>
                </p><p className="c0"><span className="c1">15.3. Federal Arbitration Act </span></p><p className="c0"><span className="c1">You and Steem Crawl agree that these Terms affect interstate commerce and that the enforceability of this Section 14 shall be governed by, construed and enforced, both substantively and procedurally, by the Federal Arbitration Act, 9 U.S.C. &sect;
                    1 et seq. (the &ldquo;FAA&rdquo;) to the maximum extent permitted by applicable law.</span></p><p className="c0"><span className="c1">15.4. Process</span>
                </p><p className="c0"><span className="c1">You and Steem Crawl agree that you will notify each other in writing of any Dispute within thirty (30) days of when it arises so that the parties can attempt, in good faith, to resolve the Dispute informally. Notice to Steem Crawl shall be provided by filling out the form available at https://steemcrawl.com/contact/ or sending an email to </span><span
                    className="c4">steemcrawl@mail.com</span><span className="c1">. Your notice must include: (1) your name, postal address and email address; (2) a description of the nature or basis of the Dispute; and (3) the specific relief that you are seeking. If you and Steem Crawl cannot agree how to resolve the Dispute within thirty (30) days of Steem Crawl receiving the notice, either you or Steem Crawl may, as appropriate pursuant to this Section 14, commence an arbitration proceeding or file a claim in court. You and Steem Crawl agree that any arbitration or claim must be commenced or filed within one (1) year after the Dispute arose; otherwise, you and Steem Crawl agree that the claim is permanently barred (which means that you will no longer have the right to assert a claim regarding the Dispute). You and Steem Crawl agree that: (a) any arbitration will occur in San Francisco County, California; (b) arbitration will be conducted confidentially by a single arbitrator in accordance with the rules of JAMS; and (c) the state or federal courts in California will have exclusive jurisdiction over the enforcement of an arbitration award and over any Dispute between the parties that is not subject to arbitration. You may also litigate a Dispute in small claims court located in the county where you reside if the Dispute meets the requirements to be heard in small claims court.</span>
                </p><p className="c0"><span className="c1">15.5. Authority of Arbitrator</span></p><p className="c0"><span className="c1">As limited by the FAA, these Terms and applicable JAMS rules, the arbitrator will have: (a) the exclusive authority and jurisdiction to make all procedural and substantive decisions regarding a Dispute; and (b) the authority to grant any remedy that would otherwise be available in court. The arbitrator may only conduct an individual arbitration and may not consolidate more than one individual&rsquo;
                    s claims, preside over any type of class or representative proceeding or preside over any proceeding involving more than one individual.</span>
                </p><p className="c0"><span className="c1">15.6. Rules of JAMS</span></p><p className="c0"><span className="c1">The rules of, and additional information about, JAMS are available on the JAMS website at </span><span
                    className="c4"><a className="c3"
                                      href="https://www.google.com/url?q=http://www.jamsadr.com/&amp;sa=D&amp;ust=1461884744556000&amp;usg=AFQjCNGyIPoxCZmvcVtmcAa4IxnRo2Rb4Q">http://www.jamsadr.com/</a></span><span
                    className="c1">, as may be updated from time to time. By agreeing to be bound by these Terms, you either: (a) acknowledge and agree that you have read and understand the rules of JAMS; or (b) waive your opportunity to read the rules of JAMS and any claim that the rules of JAMS are unfair or should not apply for any reason.</span>
                </p><p className="c0"><span className="c1">15.7. Severability</span></p><p className="c0"><span className="c1">If any term, clause or provision of this Section 14 is held invalid or unenforceable, it will be so held to the minimum extent required by law and all other terms, clauses or provisions will remain valid and enforceable. Further, the waivers set forth in Section 24.2 are severable from the other provisions of these Terms and will remain valid and enforceable, except as prohibited by applicable law.</span>
                </p><p className="c0"><span className="c1 h">16. Applicable Law and Venue</span></p><p className="c0"><span className="c1">These Terms and your access to and use of Steem Crawl and the Steem Crawl Content will be governed by, and construed in accordance with, the laws of California, without resort to its conflict of law provisions. To the extent the arbitration provision in Section 14 does not apply and the Dispute cannot be heard in small claims court, you agree that any action at law or in equity arising out of, or relating to, these Terms shall be filed only in the state and federal courts located in San Francisco County, California and you hereby irrevocably and unconditionally consent and submit to the exclusive jurisdiction of such courts over any suit, action or proceeding arising out of these Terms.</span>
                </p><p className="c0"><span className="c1 h">17. Termination</span></p><p className="c0"><span className="c1">Steem Crawl reserves the right, without notice and in our sole discretion, to terminate your license to access and use Steem Crawl and to block or prevent your future access to, and use of, Steem Crawl.</span>
                </p><p className="c0"><span className="c1 h">18. Severability</span></p><p className="c0"><span className="c1">If any term, clause or provision of these Terms is deemed to be unlawful, void or for any reason unenforceable, then that term, clause or provision shall be deemed severable from these Terms and shall not affect the validity and enforceability of any remaining provisions.</span>
                </p><p className="c0"><span className="c1 h">19. Questions &amp; Contact Information</span></p><p className="c0"><span className="c1">Questions or comments about Steem Crawl may be directed to <a
                    href="mailto:steemcrawl@mail.com">steemcrawl@mail.com</a></span></p><p className="c6 c9"></p>
                </div>
            </div>
        );
    }
}

module.exports = {
    path: 'terms.html',
    component: Terms
};